### ISSUE TITLE
On running the first sample code

### ISSUE THREAD

**Issue by jtagusari** [SERVIR/servir-aces#37]
Hello. 
I hope this package makes great contribution to remote sensing applications and just start reviewing this package ([joss-reviews#6729](https://github.com/openjournals/joss-reviews/issues/6729)).

I tried to run the example code but an error was thrown. Could you please let me know how to solve it or fix the source if it is a bug?

### Environment Information

-   aces version: [6a41f1a](https://github.com/SERVIR/servir-aces/commit/6a41f1a3a51b0c1a6ad8da0e7d62aeba1e5e4bbd)
-   Python version: 3.10.11
-   Operating System: Windows 11

The package was installed from GitHub, using `pip`.

### What I Did

I copied `.env.example` and renamed it as `config.env`, then tried executing the following code, shown in the "Usage" section in README.

```
from aces.config import Config
from aces.model_trainer import ModelTrainer

config_file = "config.env"
config = Config(config_file)
trainer = ModelTrainer(config)
trainer.train_model()
```

### Results (Error)

Warning and info are shown at first.

```
BASEDIR: aces
DATADIR: aces\data
using features: ['red_before', 'green_before', 'blue_before', 'nir_before', 'red_during', 'green_during', 'blue_during', 'nir_during']
using labels: ['class']
Using seed: 42
****************************************************************************
****************************** Clear Session... ****************************
WARNING:tensorflow:From c:\Users\jtagu\Desktop\review-aces\.venv\lib\site-packages\keras\src\backend\common\global_state.py:82: The name tf.reset_default_graph is deprecated. Please use tf.compat.v1.reset_default_graph instead.

****************************************************************************
****************************** Configure memory growth... ************************
 > No GPUs found
****************************************************************************
****************************** creating datasets... ************************
Loading dataset from aces\data\training/*
```

Then, an error was thrown.

```
{
	"name": "InvalidArgumentError",
	"message": "Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: aces\\\\data\\\\training/*'",
	"stack": "---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
File c:\\Users\\jtagu\\Desktop\\review-aces\\test1.qmd:7
      5 config = Config(config_file)
      6 trainer = ModelTrainer(config)
----> 7 trainer.train_model()

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\aces\\model_trainer.py:102, in ModelTrainer.train_model(self)
    100 print(\"****************************************************************************\")
    101 print(\"****************************** creating datasets... ************************\")
--> 102 self.create_datasets(print_info=self.config.PRINT_INFO)
    104 if self.config.USE_AI_PLATFORM:
    105     print(\"****************************************************************************\")

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\aces\\model_trainer.py:180, in ModelTrainer.create_datasets(self, print_info)
    171 def create_datasets(self, print_info: bool = False) -> None:
    172     \"\"\"
    173     Create TensorFlow datasets for training, testing, and validation.
    174 
   (...)
    178     Prints information about the created datasets if print_info is set to True.
    179     \"\"\"
--> 180     self.TRAINING_DATASET = DataProcessor.get_dataset(
    181         f\"{str(self.config.TRAINING_DIR)}/*\",
    182         self.config.FEATURES,
    183         self.config.LABELS,
    184         self.config.PATCH_SHAPE[0],
    185         self.config.BATCH_SIZE,
    186         self.config.OUT_CLASS_NUM,
    187         **{**self.config.__dict__, \"training\": True},
    188     ).repeat()
    190     self.VALIDATION_DATASET = DataProcessor.get_dataset(
    191         f\"{str(self.config.VALIDATION_DIR)}/*\",
    192         self.config.FEATURES,
   (...)
    197         **self.config.__dict__,
    198     ).repeat()
    200     self.TESTING_DATASET = DataProcessor.get_dataset(
    201         f\"{str(self.config.TESTING_DIR)}/*\",
    202         self.config.FEATURES,
   (...)
    207         **self.config.__dict__,
    208     )

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\aces\\data_processor.py:517, in DataProcessor.get_dataset(pattern, features, labels, patch_size, batch_size, n_classes, **kwargs)
    488 \"\"\"
    489 Get a TFRecord dataset.
    490 
   (...)
    513 * tf.data.Dataset: The TFRecord dataset.
    514 \"\"\"
    515 print(f\"Loading dataset from {pattern}\")
--> 517 dataset = tf.data.Dataset.list_files(pattern).interleave(DataProcessor.create_tfrecord_from_file)
    519 if kwargs.get(\"IS_DNN\", False):
    520     if kwargs.get(\"USE_AI_PLATFORM\", False):

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\tensorflow\\python\\data\\ops\\dataset_ops.py:1320, in DatasetV2.list_files(file_pattern, shuffle, seed, name)
   1313 condition = math_ops.greater(array_ops.shape(matching_files)[0], 0,
   1314                              name=\"match_not_empty\")
   1316 message = math_ops.add(
   1317     \"No files matched pattern: \",
   1318     string_ops.reduce_join(file_pattern, separator=\", \"), name=\"message\")
-> 1320 assert_not_empty = control_flow_assert.Assert(
   1321     condition, [message], summarize=1, name=\"assert_not_empty\")
   1322 with ops.control_dependencies([assert_not_empty]):
   1323   matching_files = array_ops.identity(matching_files)

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\tensorflow\\python\\ops\\control_flow_assert.py:102, in Assert(condition, data, summarize, name)
    100     xs = ops.convert_n_to_tensor(data)
    101     data_str = [_summarize_eager(x, summarize) for x in xs]
--> 102     raise errors.InvalidArgumentError(
    103         node_def=None,
    104         op=None,
    105         message=\"Expected '%s' to be true. Summarized data: %s\" %
    106         (condition, \"\
\".join(data_str)))
    107   return
    109 with ops.name_scope(name, \"Assert\", [condition, data]) as name:

InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: aces\\\\data\\\\training/*'"
}
```

Thanks.

**Comment by nagellette** [comment]
I'm having the same issue while testing for review: https://github.com/openjournals/joss-reviews/issues/6729. The reason probably the failure to while defining the default paths in sample `config.env`. There should be a definition to `BASEDIR` as demonstrated in https://github.com/SERVIR/servir-aces/blob/main/notebook/count_sample_size.ipynb

This portion of the README.md should be improved to a flowlessly working version.

**Environment Information**

- servir-cases version: 0.0.16
- Python version: 3.10.12
- Operating System: Ubuntu 22.04.4 LTS

The package was installed from GitHub, using pip.

**Comment by biplovbhandari** [comment]
@jtagusari and @nagellette Sorry for coming late in this, and thank you so much for reviewing the software package. As mentioned by both of you, I have updated the `README` as well as the `Usage` docs. In addition, I have linked notebooks in both of them so user can look into more details. This should help you to run the package successfully. Let me know how it goes.

@nagellette based on your comment on emphasizing servir-aces's contribution especially in the TF and GEE community, I have updated the Statement of Need section.

**Comment by jtagusari** [comment]
@biplovbhandari 

Thanks for the update.
While I have not finished my test, the following command is for Colab and should be modified if it is for local environments.

```
cd DATADIR
!gsutil -m cp -r gs://dl-book/chapter-1/* DATADIR
```

I think it should be:
```
mkdir DATADIR
gsutil -m cp -r gs://dl-book/chapter-1/* DATADIR
```


In addition, is it difficult to use smaller test data to check the functionality of the package? It is more than 16 GB and requires a lot of memory and computation. It would be great if you could prepare lightweight test cases for quick checking.

Thanks

**Comment by biplovbhandari** [comment]
@jtagusari Thanks for your comments. I have fixed this issue. For now, the README would walk you through running the DNN model which has very light datasets for you to test with.
For the other comments on the paper, we are still working on the statement of need and will update you once it's ready to review. Thanks!

**Comment by jtagusari** [comment]
@biplovbhandari
Thank you for revising the manuscript.
On the sample training program, I encountered an error and have not yet finished the training. 

The python code is as follow (not changed):
```{python}
from aces.config import Config
from aces.model_trainer import ModelTrainer

config_file = "config.env"
config = Config(config_file)
trainer = ModelTrainer(config)
trainer.train_model()
```

And the output is as follows:
```{python}
{
	"name": "InvalidArgumentError",
	"message": "Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: aces\\\\data\\\\training/*'",
	"stack": "---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
File c:\\Users\\jtagu\\Desktop\\review-aces\\test2.qmd:7
      5 config = Config(config_file)
      6 trainer = ModelTrainer(config)
----> 7 trainer.train_model()

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\aces\\model_trainer.py:102, in ModelTrainer.train_model(self)
    100 print(\"****************************************************************************\")
    101 print(\"****************************** creating datasets... ************************\")
--> 102 self.create_datasets(print_info=self.config.PRINT_INFO)
    104 if self.config.USE_AI_PLATFORM:
    105     print(\"****************************************************************************\")

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\aces\\model_trainer.py:180, in ModelTrainer.create_datasets(self, print_info)
    171 def create_datasets(self, print_info: bool = False) -> None:
    172     \"\"\"
    173     Create TensorFlow datasets for training, testing, and validation.
    174 
   (...)
    178     Prints information about the created datasets if print_info is set to True.
    179     \"\"\"
--> 180     self.TRAINING_DATASET = DataProcessor.get_dataset(
    181         f\"{str(self.config.TRAINING_DIR)}/*\",
    182         self.config.FEATURES,
    183         self.config.LABELS,
    184         self.config.PATCH_SHAPE[0],
    185         self.config.BATCH_SIZE,
    186         self.config.OUT_CLASS_NUM,
    187         **{**self.config.__dict__, \"training\": True},
    188     ).repeat()
    190     self.VALIDATION_DATASET = DataProcessor.get_dataset(
    191         f\"{str(self.config.VALIDATION_DIR)}/*\",
    192         self.config.FEATURES,
   (...)
    197         **self.config.__dict__,
    198     ).repeat()
    200     self.TESTING_DATASET = DataProcessor.get_dataset(
    201         f\"{str(self.config.TESTING_DIR)}/*\",
    202         self.config.FEATURES,
   (...)
    207         **self.config.__dict__,
    208     )

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\aces\\data_processor.py:517, in DataProcessor.get_dataset(pattern, features, labels, patch_size, batch_size, n_classes, **kwargs)
    488 \"\"\"
    489 Get a TFRecord dataset.
    490 
   (...)
    513 * tf.data.Dataset: The TFRecord dataset.
    514 \"\"\"
    515 print(f\"Loading dataset from {pattern}\")
--> 517 dataset = tf.data.Dataset.list_files(pattern).interleave(DataProcessor.create_tfrecord_from_file)
    519 if kwargs.get(\"IS_DNN\", False):
    520     if kwargs.get(\"USE_AI_PLATFORM\", False):

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\tensorflow\\python\\data\\ops\\dataset_ops.py:1320, in DatasetV2.list_files(file_pattern, shuffle, seed, name)
   1313 condition = math_ops.greater(array_ops.shape(matching_files)[0], 0,
   1314                              name=\"match_not_empty\")
   1316 message = math_ops.add(
   1317     \"No files matched pattern: \",
   1318     string_ops.reduce_join(file_pattern, separator=\", \"), name=\"message\")
-> 1320 assert_not_empty = control_flow_assert.Assert(
   1321     condition, [message], summarize=1, name=\"assert_not_empty\")
   1322 with ops.control_dependencies([assert_not_empty]):
   1323   matching_files = array_ops.identity(matching_files)

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File c:\\Users\\jtagu\\Desktop\\review-aces\\.venv\\lib\\site-packages\\tensorflow\\python\\ops\\control_flow_assert.py:102, in Assert(condition, data, summarize, name)
    100     xs = ops.convert_n_to_tensor(data)
    101     data_str = [_summarize_eager(x, summarize) for x in xs]
--> 102     raise errors.InvalidArgumentError(
    103         node_def=None,
    104         op=None,
    105         message=\"Expected '%s' to be true. Summarized data: %s\" %
    106         (condition, \"\
\".join(data_str)))
    107   return
    109 with ops.name_scope(name, \"Assert\", [condition, data]) as name:

InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b'No files matched pattern: aces\\\\data\\\\training/*'"
}
```

I may have the wrong parameters, but I am of the opinion that you should have a look at your documentation. I am posting other issues regarding this.

Thanks,

**Comment by biplovbhandari** [comment]
@jtagusari Can you let me know which page/docs you're following? The readme has the correct instructions, maybe there are others that need updating?

**Comment by jtagusari** [comment]
@biplovbhandari I tried to follow README instruction on my PC but it fails. 

1. sample data was retrieved (dnn data, using gsutil)
2. I set `DATADIR = "DATADIR"` and `MODEL_TYPE = "dnn"`
3. I tried to run the code above, but it fails

**Comment by biplovbhandari** [comment]
@jtagusari The error looks like the files were not found. Can you double check that you're setting the right path to DATADIR? If that doesn't work, I will try to make a video explaining the processes.

**Comment by jtagusari** [comment]
@biplovbhandari 
I found that the program was started after I also set `BASEDIR = ""` (please see the [config.zip](https://github.com/user-attachments/files/15912705/config.zip)).

However, another error was thrown (please note that I changed `ipython` to `python` environment to run the program):
```
************************ preparing output directory... *********************
> Saving models and results at output\unet_v1...
Traceback (most recent call last):
  File "c:\Users\jtagu\Desktop\review-aces\test.py", line 7, in <module>
    trainer.train_model()
  File "C:\Users\jtagu\Desktop\review-aces\.venv\lib\site-packages\aces\model_trainer.py", line 115, in train_model
    self.prepare_output_dir()
  File "C:\Users\jtagu\Desktop\review-aces\.venv\lib\site-packages\aces\model_trainer.py", line 154, in prepare_output_dir
    os.mkdir(self.config.MODEL_SAVE_DIR)
FileNotFoundError: [WinError 3] 指定されたパスが見つかりません。: 'output\\unet_v1'
```

Although this error should be fixed, it was understandable, so I created `output/unet_v1` folder and tried to run the program.

However, it throws another error:
```
****************************** training model... ***************************
Traceback (most recent call last):
  File "c:\Users\jtagu\Desktop\review-aces\test.py", line 7, in <module>
    trainer.train_model()
  File "C:\Users\jtagu\Desktop\review-aces\.venv\lib\site-packages\aces\model_trainer.py", line 118, in train_model
    self.start_training()
  File "C:\Users\jtagu\Desktop\review-aces\.venv\lib\site-packages\aces\model_trainer.py", line 252, in start_training
    model_checkpoint = callbacks.ModelCheckpoint(
  File "C:\Users\jtagu\Desktop\review-aces\.venv\lib\site-packages\keras\src\callbacks\model_checkpoint.py", line 191, in __init__
    raise ValueError(
ValueError: The filepath provided must end in `.keras` (Keras model format). Received: filepath=output\unet_v1/modelCheckpoint
```

Please let me know a solution if I misunderstood the instructions. If it was due to the bug of the program, please fix it. And I hope you could prepare a fixed sample program and data that can be executed without changing parameters (As I also posted as another issue). 

Thanks.

**Comment by biplovbhandari** [comment]
@jtagusari I have fixed this issue. Please try with the newer pip version. I have also updated the [`README.md`](https://github.com/SERVIR/servir-aces/blob/main/README.md) with [Installation](https://github.com/SERVIR/servir-aces?tab=readme-ov-file#installation), [Usage](https://github.com/SERVIR/servir-aces?tab=readme-ov-file#usage), [Tutorial](https://github.com/SERVIR/servir-aces?tab=readme-ov-file#tutorial), etc. This should also address the two other issues that you have opened. Let me know how it goes. Thanks!

**Comment by jtagusari** [comment]
@biplovbhandari Thank you for revising the document. The sections you have write are easy to understand. The meaning of the terms and instructions are clear. In my environment, the tutorial codes look to be working successfully.

I found a few things that may need to be corrected:
1. `mkdir DATADIR` -> `mkdir path/to/your/project/data`
2. `IMGDIR` -> `IMAGEDIR`

And I would like to ask you how to visualize and verify the results. The Tutorial instructs to employ Google, but it requires a billing account. It also introduces a `note` where the same code is provided and executed, but there are no visualized output of the results and cannot tell whether the output is correct. I hope you would let know me the way to do this. Thanks.

**Comment by biplovbhandari** [comment]
@jtagusari Thank you for your comment. I have made those two changes that you pointed out. In addition, I have also updated the relevant section of the [`README.md`](https://github.com/SERVIR/servir-aces?tab=readme-ov-file#uploading-predictions-to-gcp-and-gee) to reflect changes on how you can visualize the result. This should resolve the visualization feature. Let me know how it goes. Thanks!

**Comment by jtagusari** [comment]
@biplovbhandari I appreciate your continuous contribution to the project and improvement of the program and documentation. I have confirmed that the tutorial program works successfully, while an additional command was required in my environment (see below). Please confirm whether this command is necessary (or it may be due to my own problem) and close this issue. Thank you very much!

In my environment, the following command was necessary before `earthengine upload image`
```
earthengine set_project {my-project-name}
```
